# .readthedocs.yaml

version: 2

build:
  os: ubuntu-20.04  # The default build system used by Read the Docs (Linux-based)
  tools:
    python: "3.10"  # Use the same Python version as your local setup

python:
  install:
    - method: setuptools  # Assumes you have a `setup.py` in your project

sphinx:
  configuration: docs/conf.py
